// This file is generated by Sapper — do not edit it!
import root from '../../routes/_layout.html';
import error from '../../routes/_error.html';

const d = decodeURIComponent;

const index = {
	js: () => import(/* webpackChunkName: "index" */ '../../routes/index.html'),
	css: "__SAPPER_CSS_PLACEHOLDER:index.html__"
};

export const manifest = {
	ignore: [],

	pages: [
		{
			// index.html
			pattern: /^\/?$/,
			parts: [
				{ component: index }
			]
		}
	],

	root,

	error
};

// this is included for legacy reasons
export const routes = {};