// This file is generated by Sapper — do not edit it!
export const timestamp = 1540160678484;

export const assets = [
	"ace-logo-192.png",
	"ace-logo-512.png",
	"favicon.png",
	"global.css",
	"manifest.json"
];

export const shell = [
	"client/75ab1bf243b928ea1a39/main.js",
	"client/75ab1bf243b928ea1a39/index.1.js"
];

export const routes = [
	{ pattern: /^\/?$/ }
];